lib/portal_web/router.ex
defmodule PortalWeb.Router do
  use PortalWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: PortalWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: PortalWeb.AuthErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", PortalWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", PortalWeb do
    pipe_through [:browser, :not_authenticated]

    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", PortalWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout
  end

  scope "/", PortalWeb do
    pipe_through [:browser, :protected]

    resources "/countries", CountryController
    resources "/departments", DepartmentController
    resources "/employees", EmployeeController do
      resources "/emp_leaves", EmpleaveController
      resources "/emp_loans", EmploanController
    end
    resources "/payrolls", PayrollController
    resources "/loans", LoanController
    resources "/positions", PositionController
    resources "/claims", ClaimController
    resources "/claim_details", ClaimDetailController
    resources "/leaves", LeaveController
    resources "/loansets", LoansetController
    resources "/attendances", AttendanceController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PortalWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PortalWeb.Telemetry
    end
  end
end

lib/portal_web/controllers/session_controller.ex
defmodule PortalWeb.SessionController do
  use PortalWeb, :controller

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, conn} ->
        changeset = Pow.Plug.change_user(conn, conn.params["user"])
        changeset = %{changeset | action: :create}

        conn
        |> put_flash(:error, "Invalid email or password")
        |> render("new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    conn
    |> Pow.Plug.delete()
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/portal_web/views/pow/session_view.ex
defmodule PortalWeb.Pow.SessionView do
  use PortalWeb, :view
end

lib/portal_web/views/session_view.ex
defmodule PortalWeb.SessionView do
  use PortalWeb, :view
end

lib/portal_web/templates/session/new.html.eex
<div class="row justify-content-center fixed-height">
<div class="col-4 align-self-center">

<div class="card">
<div class="card-body bg-light">

<h4>Sign In</h4>

<%= form_for @changeset, Routes.login_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      Invalid Login Credentials.
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= link "Register", to: Routes.signup_path(@conn, :new), class: "btn btn-outline-danger" %>
    <%= submit "Sign In", class: "btn btn-outline-primary" %>
  </div>
<% end %>

</div>
</div>

</div>
</div>