lib/portal_web/router.ex
defmodule PortalWeb.Router do
  use PortalWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: PortalWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: PortalWeb.AuthErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", PortalWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", PortalWeb do
    pipe_through [:browser, :not_authenticated]

    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", PortalWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout
  end

  scope "/", PortalWeb do
    pipe_through [:browser, :protected]

    resources "/countries", CountryController
    resources "/departments", DepartmentController
    resources "/employees", EmployeeController do
      resources "/emp_leaves", EmpleaveController
      resources "/emp_loans", EmploanController
    end
    resources "/payrolls", PayrollController
    resources "/loans", LoanController
    resources "/positions", PositionController
    resources "/claims", ClaimController
    resources "/claim_details", ClaimDetailController
    resources "/leaves", LeaveController
    resources "/loansets", LoansetController
    resources "/attendances", AttendanceController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PortalWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PortalWeb.Telemetry
    end
  end
end

lib/portal/profiles/empleave.ex
defmodule Portal.Profiles.Empleave do
  use Ecto.Schema
  import Ecto.Changeset

  schema "emp_leaves" do
    field :leaveQty, :decimal
    field :leaveType, :string
    field :employee_id, :id
    # belongs_to :employee, Portal.Profiles.Employee

    timestamps()
  end

  @doc false
  def changeset(empleave, attrs) do
    empleave
    |> cast(attrs, [:leaveType, :leaveQty, :employee_id])
    |> validate_required([:leaveType, :leaveQty, :employee_id])
    |> foreign_key_constraint(:employee_id)
  end
end

lib/portal_web/controllers/empleave_controller.ex
defmodule PortalWeb.EmpleaveController do
  use PortalWeb, :controller

  alias Portal.Settings
  alias Portal.Profiles
  alias Portal.Profiles.Empleave

  def load_selections() do
    leaves = Settings.list_leaves()
    %{ leaves: leaves }
  end

  def index(conn, _params) do
    emp_leaves = Profiles.list_emp_leaves()
    render(conn, "index.html", emp_leaves: emp_leaves)
  end

  def new(conn, %{"employee_id" => employee_id}) do
    empleave = %Empleave{employee_id: employee_id}
    changeset = Profiles.change_empleave(%Empleave{}, %{employee_id: employee_id})
    map_selections = load_selections()
    render(conn, "new.html", changeset: changeset, empleave: empleave, map_selections: map_selections)
  end

  def create(conn, %{"employee_id" => employee_id, "empleave" => empleave_params}) do
    case Profiles.create_empleave(empleave_params) do
      {:ok, _empleave} ->
        conn
        |> put_flash(:info, "Employee Leave created successfully.")
        |> redirect(to: Routes.employee_path(conn, :edit, employee_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Employee Leave not added")
        render(conn, "new.html", changeset: changeset)
      # {:error, _error} ->
      #   conn
      #   |> put_flash(:error, "Employee Leave not added")
      #   |> redirect(to: Routes.employee_path(conn, :edit, employee_id))
    end
  end

  def show(conn, %{"id" => id}) do
    empleave = Profiles.get_empleave!(id)
    map_selections = load_selections()
    render(conn, "show.html", empleave: empleave, map_selections: map_selections)
  end

  def edit(conn, %{"employee_id" => _employee_id, "id" => id}) do
    empleave = Profiles.get_empleave!(id)
    changeset = Profiles.change_empleave(empleave)
    map_selections = load_selections()
    render(conn, "edit.html", empleave: empleave, changeset: changeset, map_selections: map_selections)
  end

  def update(conn, %{"employee_id" => employee_id, "id" => id, "empleave" => empleave_params}) do
    empleave = Profiles.get_empleave!(id)

    case Profiles.update_empleave(empleave, empleave_params) do
      {:ok, _empleave} ->
        conn
        |> put_flash(:info, "Employee Leave updated successfully.")
        |> redirect(to: Routes.employee_path(conn, :edit, employee_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Employee Leave not added.")
        render(conn, "edit.html", empleave: empleave, changeset: changeset)
    end
  end

  def delete(conn, %{"employee_id" => employee_id, "id" => id}) do
    empleave = Profiles.get_empleave!(id)
    {:ok, _empleave} = Profiles.delete_empleave(empleave)

    conn
    |> put_flash(:info, "Employee Leave deleted successfully.")
    |> redirect(to: Routes.employee_path(conn, :edit, employee_id))
  end
end

lib/portal_web/views/empleave_view.ex
defmodule PortalWeb.EmpleaveView do
  use PortalWeb, :view
end

lib/portal_web/templates/empleave/edit.html.eex
<div class="row">
  <%= render PortalWeb.SharedView, "sidebar.html" %>

  <div class="col-10 fixed-height px-2">
    <div class="container py-3">

    <h3>Edit Employee Leave</h3>

    <%= render "form.html", Map.put(assigns, :action, Routes.employee_empleave_path(@conn, :update, @empleave.employee_id, @empleave.id)) %>

    </div>
  </div>
</div>

lib/portal_web/templates/empleave/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="btn-toolbar pb-3 pt-1" role="toolbar" aria-label="Toolbar Actions">
    <div class="btn-group" role="group" aria-label="Standard Actions">
      <%= if assigns[:empleave] do %>
      <%= link "Back", to: Routes.employee_path(@conn, :edit, @empleave.employee_id), class: "btn btn-primary" %>
      <%= link "New", to: Routes.employee_empleave_path(@conn, :new, @empleave.employee_id), class: "btn btn-primary" %>
      <% else %>
      <%= link "Back", to: Routes.employee_path(@conn, :edit, @changeset.changes.employee_id), class: "btn btn-primary" %>
      <%= link "New", to: Routes.employee_empleave_path(@conn, :new, @changeset.changes.employee_id), class: "btn btn-primary" %>
      <% end %>
      <%= submit "Save", class: "btn btn-primary" %>
    </div>
  </div>

  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      Oops, something went wrong! Please check the errors below.
    </div>
  <% end %>

  <div class="row">
  <div class="col-6">
    <div class="card">
    <div class="card-body">

    <div class="form-group row">
      <%= label f, :employee_id, class: "col-4 col-form-label" do %>
        Employee Code
      <% end %>
      <div class="col-6">
        <%= text_input f, :employee_id, class: "form-control form-control-sm" %>
      </div>
      <%= error_tag f, :employee_id %>
    </div>

    <div class="form-group row">
      <%= label f, :leaveType, class: "col-4 col-form-label" do %>
        Leave Type
      <% end %>
      <div class="col-6">
        <%#= text_input f, :leaveType, class: "form-control form-control-sm" %>
        <%= select f, :leaveType, Enum.map(@map_selections.leaves, &{&1.name, &1.name}), prompt: "Select Leave Type", class: "form-control form-control-sm" %>
      </div>
      <%= error_tag f, :leaveType %>
    </div>

    <div class="form-group row">
      <%= label f, :leaveQty, class: "col-4 col-form-label" do %>
        Leave Qty
      <% end %>
      <div class="col-6">
        <%= number_input f, :leaveQty, class: "form-control form-control-sm" %>
      </div>
      <%= error_tag f, :leaveQty %>
    </div>

    </div>
    </div>

  </div>
  </div>

<% end %>

lib/portal_web/templates/empleave/index-disabled.html.eex
<div class="row">
  <div class="col-10 fixed-height px-2">
    <div class="container py-3">

    <h4>Employee Leaves</h4>

    <div class="btn-toolbar pb-3 pt-1" role="toolbar" aria-label="Toolbar Actions">
        <div class="btn-group" role="group" aria-label="Standard Actions">
          <span class="d-inline-block" tabindex="0" data-toggle="tooltip" data-placement="top" title="Adding of Leaves is Disabled">
            <button type="button" class="btn btn-outline-primary btn-sm" disabled>Records</button>
          </span>
        </div>
    </div>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Leave Type</th>
      <th scope="col">Leave Qty</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= if Enumerable.impl_for @emp_leaves do %>
<%= for empleave <- @emp_leaves do %>
    <tr>
      <td><%= empleave.leaveType %></td>
      <td><%= empleave.leaveQty %></td>

    </tr>
<% end %>
<% end %>
  </tbody>
</table>

  </div>
  </div>
</div>

lib/portal_web/templates/empleave/index.html.eex
<div class="row">
  <div class="col-10 fixed-height px-2">
    <div class="container py-3">

    <h4>Employee Leaves</h4>

    <div class="btn-toolbar pb-3 pt-1" role="toolbar" aria-label="Toolbar Actions">
        <div class="btn-group" role="group" aria-label="Standard Actions">
          <%= if assigns[:employee] do %>
          <%= link "New Record", to: Routes.employee_empleave_path(@conn, :new, @employee.id), class: "btn btn-outline-primary btn-sm" %>
          <% else %>
          <button type="button" class="btn btn-outline-primary btn-sm" disabled data-toggle="tooltip" data-placement="top" title="No Selected Employee">New Record</button>
          <% end %>
        </div>
    </div>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Leave Type</th>
      <th scope="col">Leave Qty</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= if Enumerable.impl_for @emp_leaves do %>
<%= for empleave <- @emp_leaves do %>
    <tr>
      <td><%= empleave.leaveType %></td>
      <td><%= empleave.leaveQty %></td>

      <td>
        <span><%= link "Show", to: Routes.employee_empleave_path(@conn, :show, @employee.id, empleave.id) %></span>
        <span><%= link "Edit", to: Routes.employee_empleave_path(@conn, :edit, @employee.id, empleave.id) %></span>
        <span><%= link "Delete", to: Routes.employee_empleave_path(@conn, :delete, @employee.id, empleave.id), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
<% end %>
  </tbody>
</table>

  </div>
  </div>
</div>

lib/portal_web/templates/empleave/new.html.eex
<div class="row">
  <%= render PortalWeb.SharedView, "sidebar.html" %>

  <div class="col-10 fixed-height px-2">
    <div class="container py-3">

    <h3>New Employee Leave</h3>

    <%= render "form.html", Map.put(assigns, :action, Routes.employee_empleave_path(@conn, :create, @changeset.changes.employee_id)) %>

    </div>
  </div>
</div>

lib/portal_web/templates/empleave/show.html.eex
<div class="row">
  <%= render PortalWeb.SharedView, "sidebar.html" %>

  <div class="col-10 fixed-height px-2">
    <div class="container py-3">

    <h3>View Employee Leave</h3>

    <div class="btn-toolbar pb-3 pt-1" role="toolbar" aria-label="Toolbar Actions">
      <div class="btn-group" role="group" aria-label="Standard Actions">
        <%= link "Back", to: Routes.employee_path(@conn, :edit, @empleave.employee_id), class: "btn btn-primary" %>
        <%= link "New", to: Routes.employee_empleave_path(@conn, :new, @empleave.employee_id), class: "btn btn-primary" %>
        <%= link "Edit", to: Routes.employee_empleave_path(@conn, :edit, @empleave.employee_id, @empleave.id), class: "btn btn-primary" %>
      </div>
    </div>

  <div class="row">
  <div class="col-6">
    <div class="card">
    <div class="card-body">

    <div class="form-group row">
      <label for="inputEmpCode" class="col-4 col-form-label">
        Employee Code
      </label>
      <div class="col-6">
        <input type="text" class="form-control form-control-sm" id="inputEmpCode" value="<%= @empleave.employee_id %>" disabled>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputLeaveType" class="col-4 col-form-label">
        Leave Type
      </label>
      <div class="col-6">
        <select class="form-control form-control-sm" id="inputLeaveType" disabled>
          <%= for leave <- @map_selections.leaves do %>
            <%= if leave.name == @empleave.leaveType do %>
              <option value="<%= leave.name %>" selected><%= leave.name %></option>
            <% else %>
              <option value="<%= leave.name %>"><%= leave.name %></option>
            <% end %>
          <% end %>
        </select>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputLeaveQty" class="col-4 col-form-label">
        Leave Qty
      </label>
      <div class="col-6">
        <input type="text" class="form-control form-control-sm" id="inputLeaveQty" value="<%= @empleave.leaveQty %>" disabled>
      </div>
    </div>

    </div>
    </div>

  </div>
  </div>

    </div>
  </div>
</div>